### PR TITLE
More utilities

### PR DESCRIPTION
**Pull request by AstrophysicsAndPython**
## Others
- [x] Is the given input an alphabet?
- [x] Is the given input numeric or not?
## Lists
- [x] Convert numeric list to list of strings.
- [x] Convert a list of strings to a numeric list.
- [x] Convert nested to a single list.
- [x] Convert a single list to a nested list.
- [x] Join N lists
- [x] Replace elements in a list 
  - [x] At index
  - [x] At values
- [x] Is one list contained within the other?
- [x] Sort a list and get its indices back

### CODE REVIEW

**Comment by AstrophysicsAndPython** [comment]
### Join N lists:
1. Can join nested tuples
2. Can work with nested lists and tuples by converting the lists to tuples
3. Can give unique values of nested tuples, and others
4. Can work with nested tuples and int/floats.

**Review by syedalimohsinbukhari — APPROVED** [review]

**Review by syedalimohsinbukhari — APPROVED** [review]

**Review by syedalimohsinbukhari — APPROVED** [review]
good

**Comment by AstrophysicsAndPython** [comment]
- [x] Fix issue with sorted in `get_object_count`, (see `ez_list` cbf63667081eb2d453be296e299aaff6c003567b line # 320)

**Review by AstrophysicsAndPython — COMMENTED** [review]
looks good to me

**Pull request merged**
